spring:
  application:
    name: collector

  datasource:
    url: jdbc:postgresql://ep-dark-paper-a4kqrcj2-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_2xFmU3YtNayA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true